Some quotes, Better safe than sorry. Use die() where possible.

diff --git a/wip/ebuild b/wip/ebuild
--- a/wip/ebuild
+++ b/wip/ebuild
@@ -6,7 +6,7 @@ umask 022
 unalias -a
 
 die() {
-	echo $*
+	echo "$@"
 	exit 1
 }
 
@@ -18,10 +18,10 @@ source_file() {
 	for fn in "$@"
 	do
 		local cwdfn="${fn##*/}"
-		if [ -e ${cwdfn} ]; then
-			source ${cwdfn}
-		elif [ "${fn:0:1}" == "/" ] && [ -e ${fn} ]; then
-			source ${fn}
+		if [ -e "${cwdfn}" ]; then
+			source "${cwdfn}"
+		elif [ "${fn:0:1}" = "/" ] && [ -e "${fn}" ]; then
+			source "${fn}"
 		else
 			die "File $fn (or local equivalent) not found. Exiting."
 		fi
@@ -33,8 +33,10 @@ source_file ebuild.conf
 export DISTDIR
  
 try() {
-	$*
-	[ $? -ne 0 ] && echo "Error running command: $*" && exit 1
+	# Wonder if it will be all right with double quotes.
+	if ! "$@"; then
+		die "Error running command: $@";
+	fi
 }
 
 pkg_setup() {
@@ -42,7 +44,7 @@ pkg_setup() {
 }
 
 src_clean() {
-	[ -d ${WORKDIR} ] && rm -rf ${WORKDIR}; install -d ${WORKDIR}; cd ${WORKDIR}
+	[ -d "${WORKDIR}" ] && rm -rf "${WORKDIR}"; install -d "${WORKDIR}"; cd "${WORKDIR}"
 }
 
 src_unpack() {
@@ -53,15 +55,16 @@ src_unpack() {
 }
 
 src_compile() {
-	cd $S; try make $MAKEOPTS 
+	# Shoudn't we drop MAKEOPTS in favor of MAKEFLAGS variable which make use by default?
+	cd "$S"; try make "$MAKEOPTS"
 }
 
 src_configure() {
-	cd $S; [ -e ./configure ] && try econf
+	cd "$S"; [ -e ./configure ] && try econf
 }
 
 src_install() {
-	cd $S; try make DESTDIR=$IMAGEDIR install
+	cd "$S"; try make DESTDIR="$IMAGEDIR" install
 }
 
 econf() {
@@ -114,7 +117,6 @@ case "${2}" in
 		src_install
 		;;
 	*)
-		echo "Please specify unpack, configure, compile or all as the second arg"
-		exit 1
+		die "Please specify unpack, configure, compile or all as the second arg"
 		;;
 esac
